services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    volumes:
      - ./django-backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./django-backend/docker.env
    depends_on:
      - broker

  broker:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: celery -A project worker -l info
    volumes:
      - ./django-backend:/app
    env_file:
      - ./django-backend/docker.env
    depends_on:
      - backend
      - broker

  scheduler:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: celery -A project beat -l info
    volumes:
      - ./django-backend:/app
    env_file:
      - ./django-backend/docker.env
    depends_on:
      - backend
      - broker
