# Generated by Django 5.2.5 on 2025-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanupreport',
            old_name='active_user_remaining',
            new_name='active_users_remaining',
        ),
        migrations.AlterField(
            model_name='cleanupreport',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
