# Generated by Django 5.2.5 on 2025-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0002_rename_active_user_remaining_cleanupreport_active_users_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupreport',
            name='was_manual',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
