# Generated by Django 5.2.5 on 2025-08-28 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0003_cleanupreport_was_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
